-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."softcartDimDate"
(
    dateid bigint NOT NULL,
    month bigint,
    monthname character varying,
    quarter bigint,
    quartername character varying,
    year bigint,
    day bigint,
    weekday bigint,
    weekdayname character varying,
    PRIMARY KEY (dateid)
);

CREATE TABLE public."softcartDimCategory"
(
    categoryid bigint NOT NULL,
    category character varying NOT NULL,
    PRIMARY KEY (categoryid)
);

CREATE TABLE public."softcartDimItem"
(
    itemid bigint NOT NULL,
    item character varying NOT NULL,
    PRIMARY KEY (itemid)
);

CREATE TABLE public."softcartDimCountry"
(
    countryid bigint NOT NULL,
    country character varying NOT NULL,
    PRIMARY KEY (countryid)
);

CREATE TABLE public."softcartFactSales"
(
    orderid bigint NOT NULL,
    itemid bigint,
    categoryid bigint,
    price double precision,
    countryid bigint,
    dateid bigint,
    PRIMARY KEY (orderid)
);

ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (categoryid)
    REFERENCES public."softcartDimCategory" (categoryid)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (itemid)
    REFERENCES public."softcartDimItem" (itemid)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (countryid)
    REFERENCES public."softcartDimCountry" (countryid)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (dateid)
    REFERENCES public."softcartDimDate" (dateid)
    NOT VALID;

END;
